# Generated by Django 4.1.2 on 2023-02-20 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='call_count',
        ),
        migrations.CreateModel(
            name='JokeCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_count', models.IntegerField(default=0)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
